// UC2.idl : IDL source for UC2
//

// This file will be processed by the MIDL tool to
// produce the type library (UC2.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(49271528-FA0A-43EB-B417-FAE48F4454B4),
	dual,
	nonextensible,
	helpstring("IUnitCon Interface"),
	pointer_default(unique)
]
interface IUnitCon : IDispatch{
	[id(1), helpstring("method CheckUnit checks whether a particular unit string is understood by the unit conversion library.")] HRESULT CheckUnit([in] BSTR unitStr, [out,retval] VARIANT_BOOL* isValid);
	[id(2), helpstring("method CheckUnits evaluates whether the unit conversion library can convert a value from the fromUnit to the toUnit.")] HRESULT CheckUnits([in] BSTR fromUnit, [in] BSTR toUnit, [out,retval] VARIANT_BOOL* isValidConversion);
	[id(3), helpstring("method ConvertUnits convert the current value in the current units to the new units")] HRESULT ConvertUnits([in] DOUBLE value, [in] BSTR currentUnits, [in] BSTR newUnits, [out,retval] DOUBLE* newValue);
};
[
	uuid(C4F6DD36-142F-4150-BE99-D03A157E4CF7),
	version(1.0),
	helpstring("UC2 0.2 Type Library")
]
library UC2Lib
{
	importlib("stdole2.tlb");
	[
		uuid(A1B6EBC0-FEB9-43C4-B006-06598D449DFD),
		helpstring("UnitCon Class")
	]
	coclass UnitCon
	{
		[default] interface IUnitCon;
	};
};
