//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinterRegressionTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\UnitsTest\\")]
        public string UnitsWorkingDir {
            get {
                return ((string)(this["UnitsWorkingDir"]));
            }
            set {
                this["UnitsWorkingDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flash_Example_ACM.json")]
        public string ACMFilename {
            get {
                return ((string)(this["ACMFilename"]));
            }
            set {
                this["ACMFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Flash_Example_AP.json")]
        public string APFilename {
            get {
                return ((string)(this["APFilename"]));
            }
            set {
                this["APFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("long.json")]
        public string LongACMFilename {
            get {
                return ((string)(this["LongACMFilename"]));
            }
            set {
                this["LongACMFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("long.json")]
        public string LongAPFilename {
            get {
                return ((string)(this["LongAPFilename"]));
            }
            set {
                this["LongAPFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFB.json")]
        public string DynamicACMFilename {
            get {
                return ((string)(this["DynamicACMFilename"]));
            }
            set {
                this["DynamicACMFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inputs_1.json")]
        public string DynamicACMInputs {
            get {
                return ((string)(this["DynamicACMInputs"]));
            }
            set {
                this["DynamicACMInputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inputs_2.json")]
        public string DynamicACMInputs_2 {
            get {
                return ((string)(this["DynamicACMInputs_2"]));
            }
            set {
                this["DynamicACMInputs_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\models\\SimpleExcelTest\\exceltest-sinter.json")]
        public string ExcelSinterJson {
            get {
                return ((string)(this["ExcelSinterJson"]));
            }
            set {
                this["ExcelSinterJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\models\\SimpleExcelTest\\exceltest-defaults.json")]
        public string ExcelSinterDefaults {
            get {
                return ((string)(this["ExcelSinterDefaults"]));
            }
            set {
                this["ExcelSinterDefaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\models\\SimpleExcelTest\\exceltest-inputs.json")]
        public string ExcelSinterInputs {
            get {
                return ((string)(this["ExcelSinterInputs"]));
            }
            set {
                this["ExcelSinterInputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\models\\SimpleExcelTest\\test-ouputs.json")]
        public string ExcelSinterOutputs {
            get {
                return ((string)(this["ExcelSinterOutputs"]));
            }
            set {
                this["ExcelSinterOutputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\models\\SimpleExcelTest\\outputs-canonical.json")]
        public string ExcelSinterCanonicalOutputs {
            get {
                return ((string)(this["ExcelSinterCanonicalOutputs"]));
            }
            set {
                this["ExcelSinterCanonicalOutputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\UnitsTest\\unitstest-sinter.json")]
        public string UnitsTestSinter {
            get {
                return ((string)(this["UnitsTestSinter"]));
            }
            set {
                this["UnitsTestSinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\UnitsTest\\unitstest-inputs.json")]
        public string UnitsTestInputs {
            get {
                return ((string)(this["UnitsTestInputs"]));
            }
            set {
                this["UnitsTestInputs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\ACM\\Flash_Example_ACM.json")]
        public string FlashACMConfig {
            get {
                return ((string)(this["FlashACMConfig"]));
            }
            set {
                this["FlashACMConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\Aspen_Plus\\Flash_Example_AP.json")]
        public string FlashAPConfig {
            get {
                return ((string)(this["FlashAPConfig"]));
            }
            set {
                this["FlashAPConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\Aspen_Plus\\Flash_Example_AP.json")]
        public string sinterConfiguration {
            get {
                return ((string)(this["sinterConfiguration"]));
            }
            set {
                this["sinterConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\Aspen_Plus\\Flash_Example.bkp")]
        public string simulationBackup {
            get {
                return ((string)(this["simulationBackup"]));
            }
            set {
                this["simulationBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\Aspen_Plus\\Flash_Example_AP.json")]
        public string jsonConfiguration {
            get {
                return ((string)(this["jsonConfiguration"]));
            }
            set {
                this["jsonConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\ACM\\Flash_Example_ACM.json")]
        public string ACMConfiguration {
            get {
                return ((string)(this["ACMConfiguration"]));
            }
            set {
                this["ACMConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\ACM")]
        public string ACMDir {
            get {
                return ((string)(this["ACMDir"]));
            }
            set {
                this["ACMDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\Flash_Example\\trunk\\Aspen_Plus\\")]
        public string APDir {
            get {
                return ((string)(this["APDir"]));
            }
            set {
                this["APDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\SinterExcelTest\\models\\SimpleExcelTest\\exceltest.xlsm")]
        public string ExcelWorksheet {
            get {
                return ((string)(this["ExcelWorksheet"]));
            }
            set {
                this["ExcelWorksheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\LongRun\\ACM\\long.json")]
        public string LongACMConfig {
            get {
                return ((string)(this["LongACMConfig"]));
            }
            set {
                this["LongACMConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\SimSinter\\Master\\test\\LongRun\\ACM\\")]
        public string LongACMDir {
            get {
                return ((string)(this["LongACMDir"]));
            }
            set {
                this["LongACMDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\LongRun\\AP\\long.json")]
        public string LongAPConfig {
            get {
                return ((string)(this["LongAPConfig"]));
            }
            set {
                this["LongAPConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\LongRun\\AP")]
        public string LongAPDir {
            get {
                return ((string)(this["LongAPDir"]));
            }
            set {
                this["LongAPDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\test\\DynamicTest")]
        public string DynamicACMDir {
            get {
                return ((string)(this["DynamicACMDir"]));
            }
            set {
                this["DynamicACMDir"] = value;
            }
        }
    }
}
